name: Suma de dos números y evaluación

on:
  push:
    branches:
      - test/*   # Solo ramas que empiecen con test/

jobs:
  suma_job:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar variables de entorno
        run: |
          echo "NUM1 = ${{ vars.NUM1 }}"
          echo "NUM2 = ${{ vars.NUM2 }}"

      - name: Sumar y evaluar resultado
        run: |
          suma=$(( ${{ vars.NUM1 }} + ${{ vars.NUM2 }} ))
          echo "La suma es: $suma"

          if [ $suma -gt 10 ]; then
            echo "El resultado es mayor a 10"
          else
            echo "El resultado es menor o igual a 10"
          fi
