name: Suma de dos números con variables de entorno del repositorio

on:
  push:
    branches:
      - test/*

jobs:
  sumar:
    name: Sumar
    runs-on: ubuntu-latest
    outputs:
      suma: ${{ steps.calcular_suma.outputs.resultado }}
    steps:
      - name: Calcular suma
        id: calcular_suma
        run: |
          suma=$(( ${{ vars.NUM1 }} + ${{ vars.NUM2 }} ))
          echo "La suma es: $suma"
          echo "resultado=$suma" >> $GITHUB_OUTPUT

  validar:
    name: Validar resultado
    runs-on: ubuntu-latest
    needs: sumar
    steps:
      - name: Validar suma
        run: |
          suma="${{ needs.sumar.outputs.suma }}"
          echo "La suma es: $suma"
          if [ $suma -gt 10 ]; then
            echo "El resultado es mayor a 10"
          else
            echo "El resultado es menor o igual a 10"
          fi

  mostrar_variables_repositorio:
    name: Mostrar variables
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar variables de entorno
        run: |
          echo "NUM1 = ${{ vars.NUM1 }}"
          echo "NUM2 = ${{ vars.NUM2 }}"
          
