name: Suma de dos números

on: [push]  # Ejecuta el workflow al hacer push a cualquier rama

jobs:
  suma_job:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar variables de entorno
        run: |
          echo "NUM1 = ${{ secrets.NUM1 }}"
          echo "NUM2 = ${{ secrets.NUM2 }}"

      - name: Sumar y evaluar resultado
        run: |
          # Sumar los números
          suma=$(( ${{ secrets.NUM1 }} + ${{ secrets.NUM2 }} ))
          echo "La suma es: $suma"

          # Condicional para evaluar la suma
          if [ $suma -gt 10 ]; then
            echo "El resultado es mayor a 10"
          else
            echo "El resultado es menor o igual a 10"
          fi
